# Generated by Django 5.0.2 on 2025-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technews',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
